# Basic
title: 郝俊生
subtitle: 个人站
description: 欢迎来到我的个人站~
# 头像里面的标题
avatarTitle: Anapodoton
# 头像里面的描述
avatarDesc: 区块链/ 密码学/ 分布式
url: "http://anapodoton.github.io"

# Comment
# comment:
#     #disqus: haojs1995
#     gitment: anapodoton.github.io
#     #uyan: 2143225  # 有言id,登录有言官网申请

comment_gitment_repo: anapodoton.github.io
comment_gitment_clientId: e03746f1f25f97a7b766
comment_gitment_clientSecret: cef15f1e424275920776e1d82dfa21b03af3f5e8

# Social
social:
    weibo: 叫我郝俊生 
    github: Anapodoton
    zhihu: anapodoton
    # juejin: xxx
    jianshu: hjs1995
    # twitter: 
    mail: haojunsheng@ruc.edu.cn


# 百度统计 
# 使用博客模板请去掉或者更换 id 
baidu:
    id: xxxx  

# Google Analytics
# 使用博客模板请去掉或者更换 id
ga:
    id: UA-139335873-1  
    host: auto  


# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}      
    - {title: 关于我, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


