# Basic
title: 郝俊生
subtitle: 个人站
description: 欢迎来到我的个人站~
# 头像里面的标题
avatarTitle: 俊语
# 头像里面的描述
avatarDesc: 区块链/ Java/ 分布式
url: "http://haojunsheng.github.io"

# 博客是否自动生成目录，false为不生成
enableToc: true

# Comment
comment:
    livere: MTAyMC80Nzg4MC8yNDM3Nw  # https://www.livere.com
    # disqus: leopard
    # uyan: 2143225  # 有言id,登录有言官网申请

# Social
social:
    weibo: 5288231404 
    github: haojunsheng
    zhihu: hjs.junyu
    toutiao: MS4wLjABAAAAd_u9Xk-nxVxhoJKDB15nb7IfsdNdopOaxkogI_HN1k0
    medium: hjs-junyu
    mail: hjs.junyu@gmail.com


# 百度统计 
# 使用博客模板请去掉或者更换 id 
baidu:
    id: xxxx  

# Google Analytics
# 使用博客模板请去掉或者更换 id
ga:
    id: UA-139335873-1  
    host: auto  


# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}      
    - {title: 关于我, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


